import { Home, Compass, BookOpen, Target, TrendingUp, User, Sparkles, Video, Settings, Shield, Bookmark, Award, Brain, BrainCircuit, History, RotateCcw, Zap } from '@/icons';
import { NavItem } from '@/types/navigation';

export const NAV_ITEMS: NavItem[] = [
  {
    id: 'home',
    label: 'Home',
    path: '/',
    icon: Home,
  },
  {
    id: 'command',
    label: 'Command Center',
    path: '/command',
    icon: Compass,
    badge: '30s Intelligence',
  },
  {
    id: 'briefing',
    label: 'Daily Briefing',
    path: '/briefing',
    icon: Sparkles,
    badge: 'Morning Intelligence',
  },
  {
    id: 'formula',
    label: 'Formula Engine',
    path: '/formula',
    icon: Zap,
    badge: 'Equations & Proofs',
  },
  {
    id: 'ncert',
    label: 'NCERT Intelligence',
    path: '/ncert',
    icon: BookOpen,
    badge: 'Interactive AI',
  },
  {
    id: 'revision',
    label: 'Smart Revision',
    path: '/revision',
    icon: RotateCcw,
    badge: 'Spaced Recall',
  },
  {
    id: 'brain',
    label: 'Rankify Brain',
    path: '/brain',
    icon: BrainCircuit,
    badge: 'AI Study Coach',
  },
  {
    id: 'replay',
    label: 'Study Replay',
    path: '/replay',
    icon: History,
    badge: 'Learning Diary',
  },
  {
    id: 'readiness',
    label: 'Exam Readiness',
    path: '/readiness',
    icon: Award,
    badge: 'Deterministic',
  },
  {
    id: 'weakness',
    label: 'Weakness Analyzer',
    path: '/weakness',
    icon: Brain,
    badge: 'Root Cause AI',
  },
  {
    id: 'study',
    label: 'Rankify Smart Engine',
    path: '/study',
    icon: BookOpen,
  },
  {
    id: 'practice',
    label: 'Practice',
    path: '/practice',
    icon: Target,
  },
  {
    id: 'mistakes',
    label: 'Mistake Notebook',
    path: '/mistakes',
    icon: Bookmark,
    badge: 'Spaced Repetition',
  },
  {
    id: 'ai',
    label: 'Rankify AI',
    path: '/ai',
    icon: Sparkles,
    badge: 'Prompt Engine',
  },
  {
    id: 'progress',
    label: 'Progress',
    path: '/progress',
    icon: TrendingUp,
  },
  {
    id: 'profile',
    label: 'Profile',
    path: '/profile',
    icon: User,
  },
  {
    id: 'settings',
    label: 'Settings',
    path: '/settings',
    icon: Settings,
  },
  {
    id: 'admin',
    label: 'Admin Console',
    path: '/admin',
    icon: Shield,
  },
];
